// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHz5MhpnKByC_S94rgjcZ5zsNMPQprlKA',
    appId: '1:520666620714:web:31442f831319a30bb17453',
    messagingSenderId: '520666620714',
    projectId: 'tonal-griffin-480105-m0',
    authDomain: 'tonal-griffin-480105-m0.firebaseapp.com',
    storageBucket: 'tonal-griffin-480105-m0.firebasestorage.app',
    measurementId: 'G-KM3Y73CPSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkxyuZ9scgbscaLsCeQcLmO9HxA4xquO4',
    appId: '1:520666620714:android:233ab6f63946d727b17453',
    messagingSenderId: '520666620714',
    projectId: 'tonal-griffin-480105-m0',
    storageBucket: 'tonal-griffin-480105-m0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgTAg48wasprnOJmiHsALpDOa_of1Ix_M',
    appId: '1:520666620714:ios:db1790dc4a8489c0b17453',
    messagingSenderId: '520666620714',
    projectId: 'tonal-griffin-480105-m0',
    storageBucket: 'tonal-griffin-480105-m0.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgTAg48wasprnOJmiHsALpDOa_of1Ix_M',
    appId: '1:520666620714:ios:db1790dc4a8489c0b17453',
    messagingSenderId: '520666620714',
    projectId: 'tonal-griffin-480105-m0',
    storageBucket: 'tonal-griffin-480105-m0.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHz5MhpnKByC_S94rgjcZ5zsNMPQprlKA',
    appId: '1:520666620714:web:fda83d6e1cbc7beeb17453',
    messagingSenderId: '520666620714',
    projectId: 'tonal-griffin-480105-m0',
    authDomain: 'tonal-griffin-480105-m0.firebaseapp.com',
    storageBucket: 'tonal-griffin-480105-m0.firebasestorage.app',
    measurementId: 'G-BS59KTQ6HV',
  );

}